### ISSUE TITLE
elasticsearch 8.2.0 package returns address validation error

### ISSUE THREAD

**Issue by schwing** [ElasticSearchCLITools/esTail#2]
Using version 8.2.0 of the elasticsearch package, as defined in https://github.com/ElasticSearchCLITools/esTail/blob/master/package.json#L13 I receive this error:

```
Elasticsearch ERROR: 2015-12-09T17:38:26Z
  Error: Unable to convert node list from undefined to hosts durring sniff. Encountered error:
  Error: node's http_address property ("10.0.1.52:9200") does not match the expected pattern /\[\/*([^:]+):(\d+)\]/.
```

Version 10.0.1 has an updated method for this check: https://github.com/elastic/elasticsearch-js/blob/v10.0.1/src/lib/nodes_to_host.js

Updating the elasticsearch dependency at https://github.com/ElasticSearchCLITools/esTail/blob/master/package.json#L13 to the latest version (10.0.1 at the time of this writing) and running `npm install` to update the dependency resolves the issue:
`"elasticsearch": "^10.0.1",`

**Comment by mkozjak** [comment]
+1

**Comment by eperry** [comment]
I will start looking at this, I run on an older Elasticsearch, but am updating to 2.0 as we speak.

**Comment by eperry** [comment]
sorry for the delay did not realize it was such a simple fix. I set it to elasti. csearch 9.0.1  and it is working with the latest download of Elasticsearch.
