### ISSUE TITLE
Elastic Search 5.4.2 - ERR: [parsing_exception]

### ISSUE THREAD

**Issue by ctataryn** [ElasticSearchCLITools/esTail#4]
I tried using esTail against my ES instance however I get the following error:

`$ node ./esTail.js --hostport=my-es-server:9200 --index=ereglog-dev-2017.07.31`
`Connected to Elasticsearch cluster.`
`ERR:[parsing_exception] no [query] registered for [missing], with { line=1 & col=132 } :: {"path":"/ereglog-dev-2017.07.31/_search","query":{"scroll":"30s","search_type":"scan","size":100},"body":"{\"query\":{\"bool\":{\"must\":[{\"range\":{\"@timestamp\":{\"gt\":\"now-10m\",\"to\":\"now\"}}}],\"must_not\":[{\"constant_score\":{\"filter\":{\"missing\":{\"field\":\"message\"}}}},{\"constant_score\":{\"filter\":{\"missing\":{\"field\":\"@timestamp\"}}}}],\"should\":[]}},\"sort\":{\"@timestamp\":{\"order\":\"asc\"}}}","statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"parsing_exception\",\"reason\":\"no [query] registered for [missing]\",\"line\":1,\"col\":132}],\"type\":\"parsing_exception\",\"reason\":\"no [query] registered for [missing]\",\"line\":1,\"col\":132},\"status\":400}"}`

Is this something I'm doing wrong, or is `esTail` not compatible with v5.4.2?

**Comment by aiso-net** [comment]
It looks like you have the same problem as me, and it appears your correct. The author needs to update the code for the newer versions of ES per:

https://github.com/ongr-io/ElasticsearchDSL/issues/176

**Comment by aiso-net** [comment]
It appears I was able to fix it until the author changes it, replace the esTail/default.search with this one attached. Make sure to rename it from default.search.txt to default.search
[default.search.txt](https://github.com/ElasticSearchCLITools/esTail/files/1799572/default.search.txt)

**Comment by eperry** [comment]
Thanks @aiso-net for the default.search.txt. I have replaced it.
